version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

submodules:
  include: all
  recursive: true

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/source/requirements.txt