all: base-all acmg-2015-all ave-2024-all aac-2017-all ccv-2022-all

clean: base-clean acmg-2015-clean ave-2024-clean aac-2017-clean ccv-2022-clean

base-all:
	(cd va-spec/base; make all)

base-clean:
	(cd va-spec/base; make clean)

acmg-2015-all:
	(cd va-spec/acmg-2015; make all)

acmg-2015-clean:
	(cd va-spec/acmg-2015; make clean)

ave-2024-all:
	(cd va-spec/ave-2024; make all)	

ave-2024-clean:
	(cd va-spec/ave-2024; make clean)

aac-2017-all:
	(cd va-spec/aac-2017; make all)	

aac-2017-clean:
	(cd va-spec/aac-2017; make clean)

ccv-2022-all:
	(cd va-spec/ccv-2022; make all)	

ccv-2022-clean:
	(cd va-spec/ccv-2022; make clean)