This directory is where the metaschema tooling will place an autogenerated rst file 
for each class in the Core IM, which render content from the core-im-source.yaml file 
as markdwon to be imported into the RTD pages in docs/source (specifically, a class 
definition and class attribute table). e.g., the equivalent directory for the metakb-cvc 
model is [here](https://github.com/ga4gh/va-spec/tree/metakb-cvc/schema/defs/annotation), and 
for the vrs model is [here](https://github.com/ga4gh/vrs/tree/8e04083d4ea26bd2883421bba67e2de900f73cb0/schema/defs/vrs).
